remote_theme: gildasio/darcli
# Site specific settings
title: "FlawCon 2019"
name: "FlawCon 2019"
keywords: "Infosec, Open Source, Huddersfield"
baseurl: ""
url: "https://flawcon.xyz"
description: "FlawCon 2019"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
twitter: flawcon

# Build settings
markdown: kramdown
permalink: /:categories/:title/
